#!/bin/sh
#$Id: pdf2text 4305 2006-12-07 03:36:05Z tv.raman.tv $
#

if which pdftotext   > /dev/null
then
    tempfile=/tmp/pdftotext-$$.pdf
    cat > $tempfile
    pdftotext -layout $tempfile - | cat -s 
    rm -f $tempfile
    exit 0
else 
    echo "pdftotext not found --install package XPDF."
    exit 1
fi
