(defvar email-alist '(("Agatha" . "agatha_wicca@hotmail.com")
		      ("Anguel Dimov" . "clanwje@hotmail.com")
		      ("Anh" . "little_miss0167@hotmail.com")
		      ("Anisa Khan" . "akhan31@gmail.com")
		      ("Audley Salmon" . "audley.salmon@tdsb.on.ca")
		      ("Ben" . "chronologix@gmail.com")
		      ("Brenda" . "illusionz_babi3@hotmail.com")
		      ("Charlie Katrycz" . "katrycz_c@hotmail.com")
		      ("Chester Yao" . "h1yao@hotmail.com")
		      ("Chuyang" . "chuchuliu@hotmail.com")
		      ("Cristobal" . "lilcris_leaf_fan@hotmail.com")
		      ("Curtis Huang" . "c.st.huang@gmail.com")
		      ("Danielle Swaine" . "stilts_22_4ever@hotmail.com")
		      ("Darien Spencer" . "darien_spencer@hotmail.com")
		      ("David Wolever" . ("david@wolever.net" "wolever@ftml.net"))
		      ("Devin Campbell" . "pop_corn_playerz72@hotmail.com")
		      ("Dr. James Whitfield" . "pthosteo@rogers.com")
		      ("Drake Guo" . "aesthetic.darkness@gmail.com")
		      ("Elexa St. John-Saaltink" . "elexa.sjs@gmail.com")
		      ("Ezra" . "kylekataran@yahoo.ca")
		      ("Felipe Humana-Peredes" . "chilenogrande@hotmail.com")
		      ("Gambit Mailing List" . "gambit-list@iro.umontreal.ca")
		      ("Geoff Kavanagh" . "gkavanagh@oise.utoronto.ca")
		      ("Greg" . "elfmaster@gmail.com")
		      ("Ian Esquivel" . "Ian.Esquivel@tdsb.on.ca")
		      ("Jacob Thompson" . "megaman66665@gmail.com")
		      ("Jaimie" . "stupidon_a_stick@hotmail.com")
		      ("Jennifer" . "krazy_bunnie@hotmail.com")
		      ("Jeremy Large" . "entarotassadar666@hotmail.com")
		      ("Jeremy Merkur" . "jaxxerz@gmail.com")
		      ("John Cash" . ("john.cash@bell.ca" "john_w_cash@yahoo.ca"))
		      ("Jonny Sun" . "jonny_sun@hotmail.com")
		      ("Julie and Steve" . "whitfield6@sympatico.ca")
		      ("Justin Kim" . "cyberpunk_89@hotmail.com")
		      ("Kalev Nisbet" . "kalev.nisbet@gmail.com")
		      ("Kalev" . "i_hate_math_4@hotmail.com")
		      ("Karen Ngo" . "karen.ngo@gmail.com")
		      ("Karen" . "crazy_lady_29@hotmail.com")
		      ("Kelly" . "kinky_31@hotmail.com")
		      ("Khindria Vivek" . "Vivek.Khindria@cibc.ca")
		      ("Laura" . "pipi_longstocking_24@hotmail.com")
		      ("Leah Chiang" . "leah1989kat@hotmail.com")
		      ("Lindsay Ashwin" . "lashwin@yahoo.com")
		      ("Marc Feeley" . "feeley@iro.umontreal.ca")
		      ("Maurice" . "mdevries@hotmail.com")
		      ("Max Kinsella" . ("maxkinsella@gmail.com" "traffic_in_the_sky_@hotmail.com"))
		      ("Me" . "james.nvc@gmail.com")
		      ("Michael Farley" . "michael.farley@tel.tdsb.on.ca")
		      ("Mike" . "cyborg1260@hotmail.com")
		      ("Misiu Godfrey" . "misiug@hotmail.com")
		      ("Neil Langley" . "neilyoko2@yahoo.ca")
		      ("Peter" . "pete@cs.toronto.edu")
		      ("Rajish Uthralingkam" . "urajish2002@hotmail.com")
		      ("Rodrigo Vasquez" . "unevenlines@gmail.com")
		      ("Ross Boutilier" . "ross.boutilier@ns.sympatico.ca")
		      ("Shuan Chasin" . "shaunchasin@gmail.com")
		      ("Shawn Bodh" . "shawnbodh@hotmail.com")
		      ("Shirley" . "shirl4ever10@hotmail.com")
		      ("Stephen Sealie" . "lord-vader@rogers.com")
		      ("Steven Bukal" . "katanascorner@hotmail.com")
		      ("Susy" . "peachy_dream64@hotmail.com")
		      ("Tyson" . "dim_master_tys@hotmail.com")
		      ("Victor Popov" . "filmbluffppv@yahoo.ca")
		      ("Vivek Khindria" . "Vivek.Khindria@cibc.com")
		      ("Vlad Turda" . "ssjgogetta@hotmail.com")
		      ("Wasifa Zarin" . "wasifa_zarin@hotmail.com")
		      ("Zak Leverton" . "zleverton@hotmail.com")
		      ("Piper MacFadyen" . "piper.macfadyen@gmail.com")
		      ))

(defun insert-email-addr (name)
  "Insert the email address of NAME.  If there is more than one occurence of NAME in EMAIL-ALIST, offer a choice"
  (interactive
   (let (name)
     (setq name (completing-read "Name: " email-alist nil t))
     (list name)))
  (let ((addr (cdr (assoc-string name email-alist))))
    (if (listp addr)
	(insert (completing-read "Choose address: " addr nil t))
      (insert addr))))